version: 2.1

jobs:
  build: # name of your job
    machine:
      image: windows-default
    resource_class: windows.medium
    steps:
        - checkout
        - run:
            command: Write-Host 'Hello, Windo ws'
            shell: powershell.exe -ExecutionPolicy Bypass
        - run:
            command: curl http://169.254.169.254/latest/meta-data/ami-id
            shell: bash.exe
        - run:
            command: curl -s http://169.254.169.254/latest/dynamic/instance-identity/document
            shell: bash.exe
        - run:
            command: curl http://169.254.169.254/latest/meta-data/ami-launch-index
            shell: bash.exe
        - run:
            command: curl https://www.google.com
            shell: bash.exe
        - run:
            command: curl https://runner.circleci.com
            shell: bash.exe