version: 2.1

jobs:
  build: # name of your job
    machine:
      image: windows-default
      resource_class: windows.large
    parallelism: 1
    steps:
      # Commands are run in a Windows virtual machine environment
        - checkout
        - run: Write-Host 'Hello, Windows'
