version: 2.1

jobs:
  build: # name of your job
    machine:
      image: windows-default
    resource_class: windows.medium
    steps:
      # Commands are run in a Windows virtual machine environment
        - checkout
        - run:
          command: Write-Host 'Hello, Windows'
          shell: powershell.exe -ExecutionPolicy Bypass
        - run:
          command: curl http://169.254.169.254/latest/meta-data/ami-launch-index
          shell: bash.exe